language: python
sudo: false
python:
    - 2.7
    - pypy
install:
    - pip install -U pip setuptools
    - pip install -U -e .[test]
script:
    - zope-testrunner --test-path=src
notifications:
    email: false
cache: pip
